apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca
  namespace: fabric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ca
  template:
    metadata:
      labels:
        app: ca
    spec:
      containers:
      - name: ca
        image: hyperledger/fabric-ca:latest
        ports:
        - containerPort: 7054
---
apiVersion: v1
kind: Service
metadata:
  name: ca
  namespace: fabric
spec:
  ports:
  - port: 7054
    targetPort: 7054
  selector:
    app: ca
