apiVersion: v1
kind: Service
metadata:
  name: fabric-peer
  namespace: blockchain
spec:
  selector:
    app: fabric-peer
  ports:
    - name: grpc-peer
      protocol: TCP
      port: 7051
      targetPort: 7051
    - name: chaincode
      protocol: TCP
      port: 7052
      targetPort: 7052
  type: ClusterIP
