apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer0-org1
  namespace: fabric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: peer0-org1
  template:
    metadata:
      labels:
        app: peer0-org1
    spec:
      containers:
      - name: peer
        image: hyperledger/fabric-peer:latest
        ports:
        - containerPort: 7051
---
apiVersion: v1
kind: Service
metadata:
  name: peer0-org1
  namespace: fabric
spec:
  ports:
  - port: 7051
    targetPort: 7051
  selector:
    app: peer0-org1
